services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    container_name: producer
    env_file: ./producer/.env
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
    restart: unless-stopped

  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    container_name: consumer
    env_file: ./consumer/.env
    depends_on:
      - rabbitmq
    restart: unless-stopped
